export type {
  AppConfig,
  PromptExample,
  RuntimeState,
  RuntimeStatus,
  SessionConfig,
  TerminalConfig,
  TerminalScreenProgress,
  TerminalOutputEvent,
  TerminalBufferType,
  TerminalSnapshotMode,
  TerminalSize,
  WsClientMessage,
  WsServerMessage,
} from "@termrail/shared";
